node {
    stage('Checkout'){
        checkout([$class: 'GitSCM', 
        branches: [[name: '*/main']], 
        extensions: [], 
        userRemoteConfigs: [[credentialsId: 'github_token', 
        url: 'https://github.com/SantiPilot/bootcampdevops-app.git']]])
        sh "ls -la"
    }
}